export const constantMessage = {
    ChainFrom: "Chain Id From",
    ChainTo : "Chain Id To",
    Amount : "Amount",
    RPC : "RPC",
    SenderAddress : "Sender Address",
    InsufficientAllowance : "Insufficient allowance",
    ApproveToken : "Approving token",
    ApproveNonce : "Approve nonce current",
    ApproveGas : "Approve gasPrice",
    ApproveEstimate : "Approve estimateGas",
    ApproveTx : "Approve tx",
    ApproveSing : "Approve signed tx",
    ApproveResult : "Approve result",
    Test : "Test send",
    SendNonce : "Send nonce current",
    SendGas : "Send gasPrice",
    SendEst : "Send Estimate Gas",
    SendTx : "Send Tx",
    SendSign : "Send signed tx",
    SendRes : "Send Result",
    Submission : "SUBMISSION ID",
    Success : "Success",
    NonceCurr : "Nonce current",
    GasPri : "Gas Price",
    Estimate : "Estimate Gas",
    Tx : "Tx",
    Sign : "Signed Tx",
    Res : "Result",
    Debridge : "DEBRIDGE_IDs",
    Token : "Token",
    SubmissionAlready : "Submission already used",
    TestCl : "Test Claim",
    MustBe : "Must be called from chain 'from",
    SendErr : "Sent event is not found",
    ClaimTim : "claimedTimes ",
    ThisAdrress : "The address is already controlling",
    IncrementorProxy : "incrementorScripts proxy deployed to:",
    IncrementorScript : "incrementorScripts implementation deployed to:"
  };